### PR TITLE
Correct test object

### PR DESCRIPTION
**Pull request by elysableu**
Corrected the test GameTeams object

### CODE REVIEW

**Comment by shadeauchristensen** [comment]
Woohoo!!!!

**Comment by mhaefling** [comment]
Everything looks good!

**Review by shadeauchristensen — COMMENTED** [review]
Great job!!!!

**Review by mhaefling — APPROVED** [review]
Everything looks good!

**Review by JacksonBick — APPROVED** [review]
looks great! Proud of you guys

**Pull request merged**
