### PR TITLE
game_statable_stat

### PR DESCRIPTION
**Pull request by mhaefling**
Created game_statable_spec
checking all 5 methods of the GameStatable module.

### CODE REVIEW

**Review by JacksonBick — APPROVED** [review]
ugh

**Comment by shadeauchristensen** [comment]
Remember when it was the return true... 'o_o

**Review by shadeauchristensen — COMMENTED** [review]
Done!!! Way to go!

**Review by elysableu — APPROVED** [review]
Awesome tests!  And great helper methods

**Pull request merged**
