### PR TITLE
Elysa stat tracker

### PR DESCRIPTION
**Pull request by elysableu**
Add tests for game, team, and game_teams object classes. Adjust the initialization arguments in game_teams.
Update spec_helper

### CODE REVIEW

**Comment by shadeauchristensen** [comment]
rock on dude!!!

**Comment by mhaefling** [comment]
Everything is looking good so far. Thanks Elysa

**Review by JacksonBick — COMMENTED** [review]
Thanks elysa. that was a lot of typing

**Review by shadeauchristensen — COMMENTED** [review]
Reviewed

**Pull request merged**
