### PR TITLE
added test and method for count_of_teams

### PR DESCRIPTION
**Pull request by shadeauchristensen**
added method and test for the count_of_teams

*look for commented out code matt wrote!!!! read all commented out before deleting

### CODE REVIEW

**Comment by shadeauchristensen** [comment]
commented line is in league_statable_spec.rb starting @ line:19

**Review by mhaefling — APPROVED** [review]
Good stuff

**Review by elysableu — APPROVED** [review]
Keep working!  You're heading in a good direction

**Review by JacksonBick — APPROVED** [review]
Great

**Pull request merged**
