### PR TITLE
Elysa refactor

### PR DESCRIPTION
**Pull request by elysableu**
Started to refactor: 
moved methods to be in order of assignment
moved all helper methods into bottom half of files and in order of use

### CODE REVIEW

**Comment by elysableu** [comment]
Reorganized spec files to follow same structure:
All assignment method tests in order of assignment
All helper methods moved to bottom of file and in order of use

**Review by JacksonBick — APPROVED** [review]
looks great

**Review by mhaefling — APPROVED** [review]
Thanks for organizing all this.

**Comment by shadeauchristensen** [comment]
OH YEAH!!!!!!

**Review by shadeauchristensen — COMMENTED** [review]
Great job!

**Pull request merged**
